<a href="https://colab.research.google.com/github/Prasannakolapkar/DSBDA/blob/main/Practical1-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.array([2, 3, 5, 7, 10])

In [ ]:
print(x)

[ 2  3  5  7 10]


In [ ]:
type(x)


numpy.ndarray

In [ ]:
x=np.array(([2,5,7,10]),dtype="float")

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x = np.zeros((3, 4))

In [ ]:
print(x)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
x=np.ones((3,4))

In [ ]:
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
x = np.full((3, 4), 7)


In [ ]:
print(x)


[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
x=np.eye(3,3)


In [ ]:
print(x)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
x = np.arange(2, 10, 3)


In [ ]:
print(x)

[2 5 8]


In [ ]:
x =np.linspace(7, 10, 10)

In [ ]:
print(x)

[ 7.          7.33333333  7.66666667  8.          8.33333333  8.66666667
  9.          9.33333333  9.66666667 10.        ]
